"use client";
import {useCallback,useEffect,useState,useRef} from 'react';
import {api} from '../../../lib/api';
import {type Catalogue,type Content,type Tag,type Locale,type Version,blankVersion} from '../../../lib/atlas';
import {timeline} from '../../../lib/atlas-public';
import RelationPicker from '../../components/relation-picker';
import '../../atlas.css';
import './studio.css';
const empty:Catalogue={tags:[],contents:[],companies:[],products:[]};
const newContent=():Content=>({id:'',revision:0,kind:'article',brand:'intheloop',section:'reporting',source_url:'',date:new Date().toISOString().slice(0,10),audio_language:'zh',guests:'',duration:'',company_ids:[],tag_ids:[],resources:[],versions:{zh:{...blankVersion,destination:'external'},en:{...blankVersion,destination:'hosted'}}});
const newTag=():Tag=>({id:'',revision:0,slug:'tag-'+crypto.randomUUID().slice(0,8),name_zh:'',name_en:'',dimension:'technology',tag_type:'topic',description_zh:'',description_en:'',map_visible:false,map_level:'secondary',parent_ids:[],related_tag_ids:[],aliases:[],website:'',visible_locales:['zh','en']});
function classify(url:string):Content['kind'] {try{const h=new URL(url).hostname;return h==='xiaoyuzhoufm.com'||h.endsWith('.xiaoyuzhoufm.com')||h==='podcasts.apple.com'||h==='open.spotify.com'?'podcast':'article'}catch{return 'article'}}
function isXiaoyuzhou(url:string){try{const h=new URL(url).hostname;return h==='xiaoyuzhoufm.com'||h.endsWith('.xiaoyuzhoufm.com')}catch{return false}}
function sourceLabel(url:string){try{const host=new URL(url).hostname;return host==='mp.weixin.qq.com'?'微信文章':classify(url)==='podcast'?'播客链接':'网站文章'}catch{return '原文链接'}}
export default function Studio(){
 const [data,setData]=useState<Catalogue>(empty),[tab,setTab]=useState<'upload'|'contents'|'tags'|'skill'>('upload'),[content,setContent]=useState<Content|null>(null),[tag,setTag]=useState<Tag|null>(null),[lang,setLang]=useState<Locale>('zh'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false),[model,setModel]=useState(''),[models,setModels]=useState<{id:string;name:string}[]>([]),[configured,setConfigured]=useState(false),[modelNotice,setModelNotice]=useState(''),[editorialSkill,setEditorialSkill]=useState('');
 const [auth,setAuth]=useState<{authenticated:boolean;setup_required?:boolean}|null>(null);
 const [confirmation,setConfirmation]=useState('');
 const [confirmationResolver,setConfirmationResolver]=useState<((yes:boolean)=>void)|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const active=tab==='tags'?tag:tab==='skill'?true:content;
 const dirty=typeof active==='object'&&!!active&&JSON.stringify(active)!==JSON.stringify(data[tab==='tags'?'tags':'contents'].find(r=>r.id===active.id));
 useEffect(()=>{if(confirmation&&!dialog.current?.open)dialog.current?.showModal()},[confirmation]);
 function ask(text:string){return new Promise<boolean>(resolve=>{setConfirmationResolver(()=>resolve);setConfirmation(text)})}
 function answer(yes:boolean){dialog.current?.close();setConfirmation('');confirmationResolver?.(yes);setConfirmationResolver(null)}
 const refresh=useCallback(async()=>{const d=await api<Catalogue>('/atlas');setData(d);setLoaded(true);return d},[])
 const initialize=useCallback(async()=>{if(new URLSearchParams(location.search).get('library')==='tags')setTab('tags');const [d,m,s]=await Promise.all([refresh(),api<{models:{id:string;name:string}[];configured:boolean;notice?:string}>('/atlas/models'),api<{instructions:string}>('/atlas/editorial-skill')]);setData(d);setModels(m.models);setConfigured(m.configured);setModelNotice(m.notice||'');setEditorialSkill(s.instructions)},[refresh])
 useEffect(()=>{api<{authenticated:boolean;setup_required?:boolean}>('/auth/me').then(s=>{setAuth(s);if(s.authenticated)void initialize().catch(e=>setNotice(e.message));else window.location.replace('/ops')}).catch(()=>window.location.replace('/ops'))},[initialize]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await fn()}catch(e){setNotice(e instanceof Error?e.message:'操作失败')}finally{setBusy(false)}}
 async function leave(){return !dirty||await ask('当前修改尚未保存，是否放弃这些修改？')}
 async function openContent(c:Content|null){if(busy||!await leave())return;setTab(c?'contents':'upload');setContent(c||newContent());setTag(null);setLang('zh');setNotice('')}
 async function openTag(t:Tag|null){if(busy||!await leave())return;setTab('tags');setTag(t||newTag());setContent(null);setNotice('')}
 function patch(p:Partial<Content>){if(!busy)setContent(c=>c?{...c,...p}:c)}
 function tpatch(p:Partial<Tag>){if(!busy)setTag(t=>t?{...t,...p}:t)}
 const version=content?.versions[lang]||blankVersion;
 const englishAllowed=!!content&&content.section!=='overseas'&&!content.chinese_only;
 function vpatch(p:Partial<Version>){if(content)patch({versions:{...content.versions,[lang]:{...version,...p}}})}
 async function translate(c:Content,selected:string){
  if(c.section==='overseas'||c.chinese_only)return c;
  if(!selected||!configured)throw new Error('请先选择已配置的模型');
  const zh=c.versions.zh||blankVersion;
  if(!zh.body.trim())throw new Error('请先提取或粘贴需要转换的文字；播客音频不参与转换');
  setNotice('正在生成英文文字稿…');
  const r=await api<{version:Version;model:string}>('/atlas/generate',{method:'POST',body:JSON.stringify({model:selected,task:'english',text:[zh.title,zh.summary,zh.body].join('\n\n')})});
  const result={...c,versions:{...c.versions,en:{...(c.versions.en||blankVersion),...r.version,destination:'hosted' as const}}};setContent(result);setLang('en');setNotice('英文草稿已生成，请核对后发布。');return result;
 }
 async function importLink(url:string,base?:Content){
  if(busy)return;
  const c=base||content||newContent();
  let parsed:URL;try{parsed=new URL(url.trim());if(!['http:','https:'].includes(parsed.protocol))throw new Error()}catch{setNotice('请粘贴完整的 http / https 链接');return}
  if(c.versions.zh?.body&&!(await ask('重新抓取会替换中文素材并重新准备英文草稿，是否继续？')))return;
  const draft:Content={...c,source_url:parsed.href,kind:classify(parsed.href),chinese_only:isXiaoyuzhou(parsed.href),brand:classify(parsed.href)==='podcast'?'linkstart':parsed.hostname==='geekpark.net'||parsed.hostname.endsWith('.geekpark.net')?'geekpark':'intheloop',versions:{...c.versions,zh:{...(c.versions.zh||blankVersion),destination:'external',external_url:parsed.href},...(isXiaoyuzhou(parsed.href)?{en:{...blankVersion,destination:'hosted' as const}}:{})}};
  setContent(draft);setLang('zh');
  await run(async()=>{
   if(draft.kind==='podcast'){setNotice(draft.chinese_only?'已识别小宇宙播客，将只发布到中文官网。可手动添加中文 transcript。':'已识别播客。填写标题、配套文字或链接即可；音频不会自动转写。');return}
   setNotice('已识别'+sourceLabel(url)+'，正在提取文字…');
   const r=await api<Version & {brand?:Content['brand'];source_account?:string}>('/atlas/import-url',{method:'POST',body:JSON.stringify({url:parsed.href})});
   const extracted={...draft,source_account:r.source_account||'',brand:r.brand||draft.brand,versions:{...draft.versions,en:{...blankVersion,destination:'hosted' as const},zh:{...draft.versions.zh!,title:r.title,summary:r.summary,body:r.body}}};
   setContent(extracted);
   if(model&&configured&&extracted.section!=='overseas'&&!extracted.versions.en?.body)await translate(extracted,model);
   else setNotice(extracted.section==='overseas'?'已提取。海外观察只发布中文链接。':'已提取文字。选定模型后生成英文，中文站保留原链接。');
  });
 }
 async function persistContent(c:Content){c={...c,versions:{...c.versions,zh:{...(c.versions.zh||blankVersion),destination:c.source_url?'external':'hosted',external_url:c.source_url},en:{...(c.versions.en||blankVersion),destination:'hosted'}}};const r=await api<{id:string;revision:number}>(`/atlas/contents${c.id?'/'+c.id:''}`,{method:c.id?'PUT':'POST',body:JSON.stringify(c)});const d=await refresh();const saved=d.contents.find(x=>x.id===r.id)!;setContent(saved);return saved}
 async function publish(locales:Locale[]){if(!content)return;await run(async()=>{const c=await persistContent(content);const done:string[]=[];try{for(const locale of locales){await api(`/atlas/contents/${c.id}/publish`,{method:'POST',body:JSON.stringify({locale,revision:c.revision})});done.push(locale==='zh'?'中文':'英文')}const d=await refresh();setContent(d.contents.find(x=>x.id===c.id)!);setNotice(done.join('与')+'已发布。')}catch(e){await refresh();throw new Error((done.length?done.join('、')+'已发布；':'')+(e instanceof Error?e.message:'发布失败'))}})}
 const matchSuggestions=content?data.tags.filter(t=>[t.name_zh,t.name_en,...(t.aliases||[])].some(n=>n&&n.length>1&&[content.versions.zh?.title,content.versions.zh?.body].join(' ').toLowerCase().includes(n.toLowerCase()))).map(t=>t.id):[];
 const suggestions=Array.from(new Set([...matchSuggestions,...data.tags.filter(t=>content?.tag_ids.includes(t.id)).flatMap(t=>t.related_tag_ids||[])]));
 const optionTags=data.tags.map(t=>({id:t.id,name:t.name_zh,keywords:[t.name_en,...(t.aliases||[])].join(' '),detail:(t.map_level==='primary'?'大':t.map_level==='medium'?'中':'小')+(t.map_visible===false?' · 地图隐藏':'')}));
 const filteredTags=data.tags.filter(t=>[t.name_zh,t.name_en,...(t.aliases||[])].join(' ').toLowerCase().includes(query.toLowerCase()));
 const tagLevels=[['primary','大标签'],['medium','中标签'],['secondary','小标签']] as const;
 if(auth===null)return <main className="loading-screen"><span className="wordmark-mini">ITL</span><p>正在打开 InTheLoop 独立站</p></main>;
 if(!auth.authenticated)return <main className="loading-screen"><span className="wordmark-mini">ITL</span><p>正在返回运营工作台</p></main>;
 return <main className="atlas admin studio">
  <dialog ref={dialog} className="confirm-dialog" onCancel={e=>{e.preventDefault();answer(false)}}><p>{confirmation}</p><div className="dialog-actions"><button autoFocus onClick={()=>answer(false)}>取消</button><button className="primary" onClick={()=>answer(true)}>继续</button></div></dialog>
  <header className="topbar"><a className="brand" href="/ops"><span className="wordmark-mini">ITL</span><span><strong>In The Loop</strong><small>运营工作台</small></span></a><nav className="tool-tabs"><a href="/ops?tool=wechat">公众号草稿</a><a href="/ops?tool=website">极客公园官网</a><a className="active" href="/ops/intheloop">InTheLoop 独立站</a><a href="/ops/audio">音频整理</a></nav><a href="/zh" target="_blank" rel="noreferrer">查看官网 ↗</a></header>
  <header className="workspace-title studio-heading"><div><p className="eyebrow">IN THE LOOP / OPERATIONS</p><h1>InTheLoop 独立站</h1></div><p>内容上传、双语编辑、标签地图与中英文官网发布</p></header>
  <div className="studio-nav"><div>{(['upload','contents','tags','skill'] as const).map(t=><button key={t} className={tab===t?'selected':''} disabled={busy} onClick={async()=>{if(await leave()){setTab(t);setContent(null);setTag(null);setQuery('');setNotice('')}}}>{t==='upload'?'上传内容':t==='contents'?'文章管理':t==='tags'?'标签管理':'英文转换规则'} {t==='contents'&&<span>{data.contents.length}</span>}{t==='tags'&&<span>{data.tags.length}</span>}</button>)}</div>{tab!=='tags'&&tab!=='skill'&&<label className="model-select">英文转换模型<select disabled={busy} value={model} onChange={e=>setModel(e.target.value)}><option value="">选择模型</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}</div>
  {modelNotice&&<p className="notice" role="status">{modelNotice}</p>}
  {notice&&<p className="notice" role="status">{notice}{!loaded&&<> · <a href="/ops">返回工作台登录</a></>}</p>}
  {loaded&&<div className={"studio-layout "+(tab==='upload'||tab==='skill'?'upload-layout':active?'has-selection':'browse-layout')}>{tab!=='upload'&&tab!=='skill'&&<aside className="studio-index"><input aria-label="搜索资料" placeholder={tab==='tags'?'搜索全部标签':'搜索内容'} value={query} onChange={e=>setQuery(e.target.value)}/><button className="index-add" disabled={busy} onClick={()=>tab==='tags'?openTag(null):openContent(null)}>＋ {tab==='tags'?'新建标签':'添加内容'}</button>{tab==='tags'?tagLevels.map(([level,label])=>{const rows=filteredTags.filter(t=>(t.map_level||'secondary')===level);return <section className={`tag-level-group level-${level}`} key={level}><h3>{label}</h3>{rows.map(t=><button key={t.id} className={'index-row '+(tag?.id===t.id?'selected':'')} onClick={()=>openTag(t)}><strong>{t.name_zh}</strong>{t.map_visible===false&&<small>地图隐藏</small>}</button>)}{!rows.length&&<p>暂无</p>}</section>}):data.contents.filter(c=>JSON.stringify(c.versions).toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.id} className={'index-row '+(content?.id===c.id?'selected':'')} onClick={()=>openContent(c)}><strong>{c.versions.zh?.title||c.versions.en?.title||'未命名内容'}</strong><small>{c.date} · {c.section==='overseas'?'海外观察':c.kind==='podcast'?'播客':'文章'} · {c.publications?.length?'已发布':'草稿'}</small></button>)}</aside>}
  <section className={"studio-editor "+(!active&&tab!=='upload'?'empty-editor':'')} aria-busy={busy}>
   {active&&tab!=='upload'&&tab!=='skill'&&<button className="back-to-index" disabled={busy} onClick={async()=>{if(await leave()){setTag(null);setContent(null);setNotice('')}}}>← 返回{tab==='tags'?'标签列表':'文章列表'}</button>}
   {tab==='skill'?<fieldset disabled={busy} className="editor-fields skill-editor"><div className="studio-editor-title"><div><p className="kicker">ENGLISH EDITORIAL SKILL</p><h2>英文转换规则</h2></div><button className="primary" onClick={()=>run(async()=>{await api('/atlas/editorial-skill',{method:'PUT',body:JSON.stringify({instructions:editorialSkill})});setNotice('英文转换规则已保存，下一次生成时生效。')})}>保存规则</button></div><p className="editor-note">这里定义英文标题、摘要和正文的写作原则。每次生成仍需单独选择模型，发布前可继续人工编辑。</p><textarea className="skill-textarea" aria-label="英文转换规则" value={editorialSkill} onChange={e=>setEditorialSkill(e.target.value)}/></fieldset>:!active?tab!=='upload'?null:<div className="studio-empty"><p className="kicker">NEW STORY</p><h2>粘贴内容链接</h2><p>粘贴文章或播客链接，整理成中英文内容。</p><input aria-label="粘贴内容链接" placeholder="https://" onPaste={e=>{const url=e.clipboardData.getData('text').trim();if(/^https?:\/\//.test(url)){e.preventDefault();void importLink(url,newContent())}}} onKeyDown={e=>{if(e.key==='Enter')void importLink(e.currentTarget.value,newContent())}}/><button onClick={()=>openContent(null)}>手动录入 / 上传文字文档 →</button></div>:

   tag?<fieldset disabled={busy} className="editor-fields"><div className="studio-editor-title"><h2>{tag.id?'编辑标签':'新建标签'}</h2><button className="primary" onClick={()=>run(async()=>{const r=await api<{id:string}>(`/atlas/tags${tag.id?'/'+tag.id:''}`,{method:tag.id?'PUT':'POST',body:JSON.stringify(tag)});const d=await refresh();setTag(d.tags.find(t=>t.id===r.id)!);setNotice('标签已保存，地图同步更新。')})}>保存标签</button></div><div className="studio-two"><label>标签名称<input value={tag.name_zh} placeholder="例如：宇树、机器人大脑" onChange={e=>tpatch({name_zh:e.target.value})}/></label><label>英文名称<input value={tag.name_en} onChange={e=>tpatch({name_en:e.target.value})}/></label></div><div className="map-choice"><span>标签层级</span><div>{(['primary','medium','secondary'] as const).map(v=><button type="button" key={v} className={(tag.map_level||'secondary')===v?'selected':''} onClick={()=>tpatch({map_level:v})}>{v==='primary'?'大':v==='medium'?'中':'小'}</button>)}</div><p>大标签汇总关联的中、小标签；中标签汇总关联的小标签。同级不扩展。</p><label className="check"><input type="checkbox" checked={tag.map_visible!==false} onChange={e=>tpatch({map_visible:e.target.checked,...(e.target.checked&&!tag.visible_locales.length?{visible_locales:['zh','en']}:{})})}/>在地图显示</label></div><RelationPicker label="关联标签" hint="关联更大的标签即归入其分类；同级标签只保留关联，不合并内容。" options={optionTags.filter(t=>t.id!==tag.id)} value={tag.related_tag_ids||[]} onChange={related_tag_ids=>tpatch({related_tag_ids})}/><section className="tag-stories"><h3>关联内容</h3>{timeline({...data,tags:data.tags.map(t=>t.id===tag.id?tag:t)},{tag:tag.slug}).map(c=><button key={c.id} className="index-row" onClick={()=>openContent(c)}><strong>{c.versions.zh?.title||c.versions.en?.title||'未命名内容'}</strong><small>{c.date} · {c.publications?.length?'已发布':'草稿'}</small></button>)}{!timeline({...data,tags:data.tags.map(t=>t.id===tag.id?tag:t)},{tag:tag.slug}).length&&<p className="editor-note">暂无关联内容。</p>}</section></fieldset>:
   content&&<fieldset disabled={busy} className="editor-fields"><div className="studio-editor-title"><h2>{content.id?'编辑内容':'添加内容'}</h2><button onClick={()=>run(async()=>{await persistContent(content);setNotice('草稿已保存，发布版本未改变。')})}>保存草稿</button></div>
    <div className="link-composer"><label>原文链接<div className="source-input"><input type="url" placeholder="粘贴微信、官网文章或播客链接" value={content.source_url} onChange={e=>patch({source_url:e.target.value})} onPaste={e=>{const url=e.clipboardData.getData('text').trim();if(/^https?:\/\//.test(url)){e.preventDefault();void importLink(url)}}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void importLink(content.source_url)}}}/><button onClick={()=>importLink(content.source_url)}>分析 →</button></div></label><div className="source-options"><span>{content.source_url?sourceLabel(content.source_url):'粘贴后自动识别并提取'}</span><label className="check"><input type="checkbox" checked={content.section==='overseas'} onChange={e=>{patch({section:e.target.checked?'overseas':'reporting'});if(e.target.checked)setLang('zh')}}/>海外观察 · 仅中文</label></div></div>
    {content.section==='overseas'&&<p className="editor-note">海外观察只发布中文。保存后会撤下这条内容已有的英文版本。</p>}
    {content.chinese_only&&<p className="editor-note">小宇宙播客只发布到中文官网。标题、摘要和中文 transcript 都可以在这里手动添加。</p>}
    <div className="edition-tabs"><div><button className={lang==='zh'?'selected':''} onClick={()=>setLang('zh')}>中文 · 原文链接</button>{englishAllowed&&<button className={lang==='en'?'selected':''} onClick={()=>setLang('en')}>英文 · 本站全文</button>}</div>{englishAllowed&&<button disabled={!configured||!model||!content.versions.zh?.body} onClick={()=>run(async()=>{if(content.versions.en?.body&&!await ask('重新生成会替换英文草稿，是否继续？'))return;await translate(content,model)})}>{content.versions.en?.body?'重新生成英文':'生成英文稿'}</button>}</div>
    {englishAllowed&&<p className="editor-note">{configured?'英文 skill 待配置，当前使用基础编辑规则；发布前请核对。':'尚未配置模型接口。可先整理中文，或手动编辑英文。'}</p>}
    <label className="story-title">标题<input value={version.title} placeholder={lang==='zh'?'中文展示标题':'English title'} onChange={e=>vpatch({title:e.target.value})}/></label><label>摘要<textarea rows={3} value={version.summary} onChange={e=>vpatch({summary:e.target.value})}/></label>
    {lang==='en'?<label>英文正文<textarea className="body-input" value={version.body} onChange={e=>vpatch({body:e.target.value,destination:'hosted'})}/></label>:<details className="studio-details" open={!content.source_url||!version.body}><summary>{content.kind==='podcast'?'中文 transcript（可选，手动添加）':'原文文字 / 配套文字'} {version.body?'· 已添加':''}</summary><p className="editor-note">{content.chinese_only?'这份文字只在中文内容页使用，不会自动翻译或发布到英文站。':'用于生成英文。中文有原链接时，读者直接前往原平台。'}</p><textarea aria-label="中文素材" className="body-input" value={version.body} onChange={e=>vpatch({body:e.target.value,destination:content.source_url?'external':'hosted'})}/><label className="file-import">上传 Word / TXT / Markdown<input type="file" accept=".doc,.docx,.txt,.md" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;e.target.value='';if(version.body&&!await ask('用文档文字替换当前中文素材？'))return;await run(async()=>{const form=new FormData();form.set('file',f);const r=await api<Version>('/atlas/import',{method:'POST',body:form});const c={...content,versions:{...content.versions,zh:{...version,...r,destination:content.source_url?'external' as const:'hosted' as const}}};setContent(c);if(model&&configured&&c.section!=='overseas'&&!c.chinese_only)await translate(c,model);else setNotice('文字已导入。')})}}/></label></details>}
    <div className="story-tags"><RelationPicker label="内容标签" options={optionTags} value={content.tag_ids} onChange={tag_ids=>patch({tag_ids})} suggestions={suggestions} hint="搜索公司、技术或品类。下方关联建议可按需加入。"/><a href="/ops/intheloop?library=tags" target="_blank" rel="noreferrer">维护标签 ↗</a></div>
    <section className="companion-editor"><div className="section-label"><h3>配套内容</h3><span>相关文章 · 公司官网 · 播客</span></div>{(content.resources||[]).map((r,i)=><div className="companion-row" key={i}><select aria-label={`配套类型 ${i+1}`} value={r.kind} onChange={e=>patch({resources:content.resources!.map((x,j)=>i===j?{...x,kind:e.target.value as typeof r.kind}:x)})}><option value="article">相关文章</option><option value="website">官方网站</option><option value="podcast">播客</option><option value="other">其他</option></select><input aria-label={`配套名称 ${i+1}`} placeholder="名称" value={r.label} onChange={e=>patch({resources:content.resources!.map((x,j)=>i===j?{...x,label:e.target.value}:x)})}/><input aria-label={`配套链接 ${i+1}`} type="url" placeholder="https://" value={r.url} onChange={e=>patch({resources:content.resources!.map((x,j)=>i===j?{...x,url:e.target.value}:x)})}/><button aria-label={`移除配套 ${i+1}`} onClick={()=>patch({resources:content.resources!.filter((_,j)=>i!==j)})}>×</button><input className="companion-en" aria-label={`配套英文名称 ${i+1}`} placeholder="英文显示名称（可选）" value={r.label_en||''} onChange={e=>patch({resources:content.resources!.map((x,j)=>i===j?{...x,label_en:e.target.value}:x)})}/></div>)}<button className="add-companion" onClick={()=>patch({resources:[...(content.resources||[]),{kind:'article',label:'',label_en:'',url:''}]})}>＋ 添加链接</button></section>
    <div className="studio-two"><label>来源（自动识别，可修改）<select value={content.brand||(content.kind==='podcast'?'linkstart':'intheloop')} onChange={e=>patch({brand:e.target.value as Content['brand'],source_account:e.target.value==='geekpark'?'极客公园':e.target.value==='linkstart'?'开始连接 LinkStart':'In The Loop'})}><option value="intheloop">In The Loop</option><option value="geekpark">极客公园 GeekPark</option><option value="linkstart">开始连接 LinkStart</option></select></label></div>
    <details className="studio-details"><summary>日期与内容类型</summary><div className="studio-two"><label>发布日期<input type="date" value={content.date} onChange={e=>patch({date:e.target.value})}/></label><label>内容类型<select value={content.kind} onChange={e=>patch({kind:e.target.value as Content['kind'],...(e.target.value==='podcast'?{brand:'linkstart'}:{})})}><option value="article">文字 / 文章</option><option value="podcast">播客</option><option value="link">其他链接</option></select></label></div></details>
    <div className="studio-publish"><p>{content.publications?.length?content.publications.map(p=>p.locale==='zh'?'中文已发布':'英文已发布').join(' · '):'尚未发布'}{dirty?' · 有未保存修改':''}</p><div><button onClick={()=>publish(['zh'])}>发布中文</button>{englishAllowed&&<button className="primary" disabled={!content.versions.en?.body||!content.versions.en?.title} onClick={()=>publish(['zh','en'])}>发布中文与英文</button>}</div>{!!content.publications?.length&&<details><summary>撤下已发布内容</summary>{content.publications.map(p=><button key={p.locale} onClick={()=>run(async()=>{if(!await ask(`撤下${p.locale==='zh'?'中文':'英文'}版本？`))return;await api(`/atlas/contents/${content.id}/publish/${p.locale}`,{method:'DELETE'});const d=await refresh();setContent(d.contents.find(c=>c.id===content.id)!);setNotice('已撤下。')})}>撤下{p.locale==='zh'?'中文':'英文'}</button>)}</details>}</div>
   </fieldset>}
  </section></div>}
 </main>
}
